

   DELETE FROM spring_batch_demo.batch_job_execution_params ;
  -- WHERE JOB_EXECUTION_ID = JOB_EXECUTION_ID AND PA

  DELETE FROM spring_batch_demo.batch_job_execution_context ;
  -- WHERE JOB_EXECUTION_ID = JOB_EXECUTION_ID AND SHORT_CONTEXT = 'SHORT_CONTEXT' AND SERIALIZED_CONTEXT = 'SERIALIZED_CONTEXT' ;
  -- 
  DELETE FROM spring_batch_demo.batch_job_execution ;
  -- WHERE JOB_EXECUTION_ID = JOB_EXECUTION_ID AND VERSION = VERSION AND JOB_INSTANCE_ID = JOB_INSTANCE_ID AND CREATE_TIME = 'CREATE_TIME' AND START_TIME = 'START_TIME' AND END_TIME = 'END_TIME' AND STATUS = 'STATUS' AND EXIT_CODE = 'EXIT_CODE' AND EXIT_MESSAGE = 'EXIT_MESSAGE' AND LAST_UPDATED = 'LAST_UPDATED' ;
  -- 
  -- 
  DELETE FROM spring_batch_demo.batch_job_instance;

  DELETE FROM spring_batch_demo.batch_step_execution ;
--   WHERE STEP_EXECUTION_ID = STEP_EXECUTION_ID AND VERSION = VERSION AND STEP_NAME = 'STEP_NAME' AND JOB_EXECUTION_ID = JOB_EXECUTION_ID AND CREATE_TIME = 'CREATE_TIME' AND START_TIME = 'START_TIME' AND END_TIME = 'END_TIME' AND STATUS = 'STATUS' AND COMMIT_COUNT = COMMIT_COUNT AND READ_COUNT = READ_COUNT AND FILTER_COUNT = FILTER_COUNT AND WRITE_COUNT = WRITE_COUNT AND READ_SKIP_COUNT = READ_SKIP_COUNT AND WRITE_SKIP_COUNT = WRITE_SKIP_COUNT AND PROCESS_SKIP_COUNT = PROCESS_SKIP_COUNT AND ROLLBACK_COUNT = ROLLBACK_COUNT AND EXIT_CODE = 'EXIT_CODE' AND EXIT_MESSAGE = 'EXIT_MESSAGE' AND LAST_UPDATED = 'LAST_UPDATED' ;

  DELETE FROM spring_batch_demo.batch_step_execution_context ;
--   WHERE STEP_EXECUTION_ID = STEP_EXECUTION_ID AND SHORT_CONTEXT = 'SHORT_CONTEXT' AND SERIALIZED_CONTEXT = 'SERIALIZED_CONTEXT' ;

 DELETE FROM spring_batch_demo.batch_job_execution_seq ;
--   WHERE ID = ID ;

  DELETE FROM spring_batch_demo.batch_job_seq ;
--   WHERE ID = ID ;




 --   Original Sqls --

-- DELETE FROM spring_batch_demo.batch_job_execution_params 
-- WHERE JOB_EXECUTION_ID = JOB_EXECUTION_ID AND PARAMETER_NAME = 'PARAMETER_NAME' AND PARAMETER_TYPE = 'PARAMETER_TYPE' AND PARAMETER_VALUE = 'PARAMETER_VALUE' AND IDENTIFYING = 'IDENTIFYING' ;

-- DELETE FROM spring_batch_demo.batch_job_execution_context 
-- WHERE JOB_EXECUTION_ID = JOB_EXECUTION_ID AND SHORT_CONTEXT = 'SHORT_CONTEXT' AND SERIALIZED_CONTEXT = 'SERIALIZED_CONTEXT' ;
-- 
-- DELETE FROM spring_batch_demo.batch_job_execution 
-- WHERE JOB_EXECUTION_ID = JOB_EXECUTION_ID AND VERSION = VERSION AND JOB_INSTANCE_ID = JOB_INSTANCE_ID AND CREATE_TIME = 'CREATE_TIME' AND START_TIME = 'START_TIME' AND END_TIME = 'END_TIME' AND STATUS = 'STATUS' AND EXIT_CODE = 'EXIT_CODE' AND EXIT_MESSAGE = 'EXIT_MESSAGE' AND LAST_UPDATED = 'LAST_UPDATED' ;
-- 
-- 
-- DELETE FROM spring_batch_demo.batch_job_instance 
-- WHERE JOB_INSTANCE_ID = JOB_INSTANCE_ID AND VERSION = VERSION AND JOB_NAME = 'JOB_NAME' AND JOB_KEY = 'JOB_KEY' ;
-- 
--   DELETE FROM spring_batch_demo.batch_step_execution 
--   WHERE STEP_EXECUTION_ID = STEP_EXECUTION_ID AND VERSION = VERSION AND STEP_NAME = 'STEP_NAME' AND JOB_EXECUTION_ID = JOB_EXECUTION_ID AND CREATE_TIME = 'CREATE_TIME' AND START_TIME = 'START_TIME' AND END_TIME = 'END_TIME' AND STATUS = 'STATUS' AND COMMIT_COUNT = COMMIT_COUNT AND READ_COUNT = READ_COUNT AND FILTER_COUNT = FILTER_COUNT AND WRITE_COUNT = WRITE_COUNT AND READ_SKIP_COUNT = READ_SKIP_COUNT AND WRITE_SKIP_COUNT = WRITE_SKIP_COUNT AND PROCESS_SKIP_COUNT = PROCESS_SKIP_COUNT AND ROLLBACK_COUNT = ROLLBACK_COUNT AND EXIT_CODE = 'EXIT_CODE' AND EXIT_MESSAGE = 'EXIT_MESSAGE' AND LAST_UPDATED = 'LAST_UPDATED' ;
-- 
--   DELETE FROM spring_batch_demo.batch_step_execution_context 
--   WHERE STEP_EXECUTION_ID = STEP_EXECUTION_ID AND SHORT_CONTEXT = 'SHORT_CONTEXT' AND SERIALIZED_CONTEXT = 'SERIALIZED_CONTEXT' ;
-- 
--   DELETE FROM spring_batch_demo.batch_job_execution_seq 
--   WHERE ID = ID ;
-- 
--   DELETE FROM spring_batch_demo.batch_job_seq 
--   WHERE ID = ID ;


